services:
    claroline.listener.site_listener:
        class: Claroline\SiteBundle\Listener\SiteListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: open_claroline_site, method: onOpen }
            - { name: kernel.event_listener, event: create_form_claroline_site, method: onCreateForm }
            - { name: kernel.event_listener, event: create_claroline_site, method: onCreate }
            - { name: kernel.event_listener, event: delete_claroline_site, method: onDelete }
            - { name: kernel.event_listener, event: copy_claroline_site, method: onCopy }